/* empty css                      */import{a as v,S as q,i as p}from"./assets/vendor-DEenWwFD.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&l(a)}).observe(document,{childList:!0,subtree:!0});function o(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(t){if(t.ep)return;t.ep=!0;const r=o(t);fetch(t.href,r)}})();const w="37013770-4fd46202a1ea52ee31e31a9bd",y=(s,e)=>{const o={params:{key:w,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:e}};return v.get("https://pixabay.com/api/",o)},f=s=>s.map(({webformatURL:e,largeImageURL:o,tags:l,likes:t,views:r,comments:a,downloads:b})=>`<a href="${o}" class="gallery-link">
    <div class="card">
    <img src="${e}" alt="${l}" loading="lazy" width="360" />
    <div class="card-info">
      <p class="card-info-item">Likes<span>${t}</span></p>
      <p class="card-info-item">Views<span>${r}</span></p>
      <p class="card-info-item">Comments<span>${a}</span></p>
      <p class="card-info-item">Downloads<span>${b}</span></p>
    </div>
    </div>
    </a>`).join(""),h=document.querySelector(".form-search"),u=document.querySelector(".gallery"),i=document.querySelector(".loader"),n=document.querySelector(".load-more-btn");let c=1,d="";const g=new q(".gallery-link",{captions:!0,captionsData:"alt",captionDelay:250});i.style.display="none";const S=async s=>{if(s.preventDefault(),u.innerHTML="",d=s.currentTarget.elements.user_query.value.trim(),c=1,n.classList.add("is-hidden"),i.style.display="block",d===""){p.warning({title:"Warning",position:"topRight",message:"Please enter a search query!"}),i.style.display="none";return}try{const{data:e}=await y(d,c);if(!e.hits.length){p.error({title:"Error",position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"});return}const o=f(e.hits);u.insertAdjacentHTML("beforeend",o),g.refresh(),h.reset(),e.totalHits>1&&(n.classList.remove("is-hidden"),n.addEventListener("click",L))}catch(e){console.log(e)}finally{i.style.display="none"}};h.addEventListener("submit",S);const L=async s=>{i.style.display="block",c++;try{const{data:e}=await y(d,c);i.style.display="none";const o=f(e.hits);u.insertAdjacentHTML("beforeend",o),m(),g.refresh(),c*15>=e.totalHits&&(p.info({title:"Info",position:"topRight",message:"We're sorry, but you've reached the end of search results."}),n.classList.add("is-hidden"),n.removeEventListener("click",L),m())}catch{p.error({title:"Error",position:"topRight",message:"Failed to load images. Please try again later."})}},m=()=>{const{height:s}=u.firstElementChild.getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"})};
//# sourceMappingURL=index.js.map
