/* empty css                      */import{a as L,S as v,i}from"./assets/vendor-DEenWwFD.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))d(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&d(l)}).observe(document,{childList:!0,subtree:!0});function o(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function d(t){if(t.ep)return;t.ep=!0;const r=o(t);fetch(t.href,r)}})();const q="37013770-4fd46202a1ea52ee31e31a9bd",y=(s,e)=>{const o={params:{key:q,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:e}};return L.get("https://pixabay.com/api/",o)},f=s=>s.map(({webformatURL:e,largeImageURL:o,tags:d,likes:t,views:r,comments:l,downloads:b})=>`<a href="${o}" class="gallery-link">
    <div class="card">
    <img src="${e}" alt="${d}" loading="lazy" width="360" />
    <div class="card-info">
      <p class="card-info-item">Likes<span>${t}</span></p>
      <p class="card-info-item">Views<span>${r}</span></p>
      <p class="card-info-item">Comments<span>${l}</span></p>
      <p class="card-info-item">Downloads<span>${b}</span></p>
    </div>
    </div>
    </a>`).join(""),h=document.querySelector(".form-search"),u=document.querySelector(".gallery"),a=document.querySelector(".loader"),c=document.querySelector(".load-more-btn");let n=1,p="";const g=new v(".gallery-link",{captions:!0,captionsData:"alt",captionDelay:250});a.style.display="none";const w=async s=>{if(s.preventDefault(),u.innerHTML="",p=s.currentTarget.elements.user_query.value.trim(),n=1,c.classList.add("is-hidden"),a.style.display="block",p===""){i.warning({title:"Warning",position:"topRight",message:"Please enter a search query!"}),a.style.display="none";return}try{const{data:e}=await y(p,n);if(!e.hits.length){i.error({title:"Error",position:"topRight",message:"Sorry, there are no images matching your search query. Please try again!"});return}const o=f(e.hits);u.insertAdjacentHTML("beforeend",o),g.refresh(),h.reset(),e.totalHits>1&&c.classList.remove("is-hidden"),n*15>=e.totalHits&&(i.info({title:"Info",position:"topRight",message:"We're sorry, but you've reached the end of search results."}),c.classList.add("is-hidden"),m())}catch{i.error({title:"Error",position:"topRight",message:"Failed to load images. Please try again later."})}finally{a.style.display="none"}};h.addEventListener("submit",w);const P=async s=>{a.style.display="block",n++;try{const{data:e}=await y(p,n);a.style.display="none";const o=f(e.hits);u.insertAdjacentHTML("beforeend",o),m(),g.refresh(),n*15>=e.totalHits&&(i.info({title:"Info",position:"topRight",message:"We're sorry, but you've reached the end of search results."}),c.classList.add("is-hidden"),m())}catch{i.error({title:"Error",position:"topRight",message:"Failed to load images. Please try again later."})}};c.addEventListener("click",P);const m=()=>{const{height:s}=u.firstElementChild.getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"})};
//# sourceMappingURL=index.js.map
